swagger: "2.0"
info:
  title: "User API"
  description: "This is the User UI"
  version: 1.0
  contact:
    email: "veronika.simic@akvelon.com"
  liscence:
    name: "Apache 2.0"
    url: "http://apache.org/"
  servers:
    -url: "http://localhost:4000/"
    description: "This is my local server"

schemes: [http, https]

paths:
  #Returns a flipped image
  /image/{imageId}:
    get:
      summary: Returns flipped image by id
      description: It returns a link for image flipped for 180 degrees and state
      parameters:
        - in: path
          name: imageId
          type: integer
          required: true
          description: Numeric ID of the flipped image to get.
      responses:
        200:
          description: Success
          schema:
              type: object
              properties:
                  id:
                    type: integer
                  state:
                    type: string
                  imgUrl: 
                    type: string
        400:
          description: Image does not exist
        500:
          description: Internal server error
  # Uploads image        
  /upload-image:
    post:
      summary: Uploads image for proccessing
      description: Upload an image to be rotated
      consumes: 
        - multipart/form-data
      parameters:
        - name: file
          in: formData
          description: The uploaded image data
          required: true
          type: file
      responses:
        200:
          description: Success
          content:
             image/*:
              schema:
                type: string
                format: binary
        400:
          description: User error
        500:
          description: Internal server error
